<?php
require_once __DIR__ . '/../inc/auth.php'; require_once __DIR__ . '/../config/database.php'; require_once __DIR__ . '/../inc/validation.php';
$id = (int) ($_GET['id'] ?? $_POST['id'] ?? 0); $statement = $pdo->prepare('SELECT * FROM requests WHERE id = ?'); $statement->execute(array($id)); $form = $statement->fetch();
if (!$form) { http_response_code(404); exit('Request not found.'); }
$page_title = 'Edit Request'; $active_page = 'requests'; $errors = array();
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); $form = array_merge($form, $_POST); $errors = validate_request($form);
    if (!$errors) { $update = $pdo->prepare('UPDATE requests SET full_name=?, address=?, barangay=?, contact_number=?, date_of_visit=?, purpose=?, assistance_type=?, amount_requested=?, remarks=? WHERE id=?'); $update->execute(array(trim($form['full_name']), trim($form['address']), trim($form['barangay']), trim($form['contact_number']), $form['date_of_visit'], trim($form['purpose']), $form['assistance_type'], (float) $form['amount_requested'], trim($form['remarks']), $id)); $_SESSION['success'] = 'Request successfully updated.'; redirect('view_request.php?id=' . $id); }
}
include __DIR__ . '/../inc/header.php';
?>
<div class="form-intro"><div><a class="back-link" href="view_request.php?id=<?= e($id); ?>"><i class="bi bi-arrow-left"></i> Back to Request</a><h2 class="section-title">Edit <?= e($form['request_id']); ?></h2></div><span class="locked-status"><i class="bi bi-lock"></i> Status changes separately</span></div><?php if ($errors): ?><div class="alert alert-error"><i class="bi bi-exclamation-circle"></i><?= e(implode(' ', $errors)); ?></div><?php endif; ?><form method="post" class="panel form-panel"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()); ?>"><input type="hidden" name="id" value="<?= e($id); ?>"><div class="form-grid"><div class="field"><label for="full_name">Full Name *</label><input id="full_name" name="full_name" value="<?= e($form['full_name']); ?>" required></div><div class="field"><label for="contact_number">Contact Number *</label><input id="contact_number" name="contact_number" value="<?= e($form['contact_number']); ?>" required></div><div class="field field-wide"><label for="address">Address *</label><input id="address" name="address" value="<?= e($form['address']); ?>" required></div><div class="field"><label for="barangay">Barangay *</label><input id="barangay" name="barangay" value="<?= e($form['barangay']); ?>" required></div><div class="field"><label for="date_of_visit">Date of Visit *</label><input id="date_of_visit" type="date" name="date_of_visit" value="<?= e($form['date_of_visit']); ?>" required></div><div class="field"><label for="assistance_type">Assistance Type *</label><select id="assistance_type" name="assistance_type" required><?php foreach (array('Financial Assistance','Medical Assistance','Educational Assistance','Solicitation','Other') as $type): ?><option <?= $form['assistance_type'] === $type ? 'selected' : ''; ?>><?= e($type); ?></option><?php endforeach; ?></select></div><div class="field"><label for="amount_requested">Amount Requested</label><div class="money-input"><span>PHP</span><input id="amount_requested" type="number" min="0" step="0.01" name="amount_requested" value="<?= e($form['amount_requested']); ?>"></div></div><div class="field field-wide"><label for="purpose">Purpose / Reason *</label><textarea id="purpose" name="purpose" rows="4" required><?= e($form['purpose']); ?></textarea></div><div class="field field-wide"><label for="remarks">Remarks</label><textarea id="remarks" name="remarks" rows="3"><?= e($form['remarks']); ?></textarea></div></div><div class="form-actions"><a href="view_request.php?id=<?= e($id); ?>" class="btn btn-light">Cancel</a><button class="btn btn-primary" type="submit"><i class="bi bi-check-lg"></i> Save Changes</button></div></form>
<?php include __DIR__ . '/../inc/footer.php'; ?>
