<?php
require_once __DIR__ . '/../inc/auth.php'; require_once __DIR__ . '/../config/database.php';
$page_title = 'Requests'; $active_page = 'requests'; $message = $_SESSION['success'] ?? ''; unset($_SESSION['success']); $errors = array();
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'delete') {
    verify_csrf();
    $statement = $pdo->prepare('DELETE FROM requests WHERE id = ?'); $statement->execute(array((int) $_POST['id']));
    $_SESSION['success'] = 'Request successfully deleted.'; redirect('requests.php');
}
$search = trim($_GET['search'] ?? ''); $status = $_GET['status'] ?? ''; $type = $_GET['assistance_type'] ?? ''; $date = $_GET['date'] ?? '';
$sql = 'SELECT * FROM requests WHERE 1=1'; $params = array();
if ($search !== '') { $sql .= ' AND (request_id LIKE ? OR full_name LIKE ? OR barangay LIKE ?)'; $term = '%' . $search . '%'; $params = array($term, $term, $term); }
if (in_array($status, array('Pending','Approved','Completed','Rejected'), true)) { $sql .= ' AND status = ?'; $params[] = $status; }
if (in_array($type, array('Financial Assistance','Medical Assistance','Educational Assistance','Solicitation','Other'), true)) { $sql .= ' AND assistance_type = ?'; $params[] = $type; }
if ($date !== '') { $sql .= ' AND date_of_visit = ?'; $params[] = $date; }
$sql .= ' ORDER BY created_at DESC'; $statement = $pdo->prepare($sql); $statement->execute($params); $requests = $statement->fetchAll();
include __DIR__ . '/../inc/header.php';
?>
<div class="welcome-row"><div><p class="muted">Browse and manage all records</p><h2 class="section-title">Request directory</h2></div><a href="add_request.php" class="btn btn-primary"><i class="bi bi-plus-lg"></i> Add New Request</a></div>
<?php if ($message): ?><div class="alert alert-success"><i class="bi bi-check-circle"></i><?= e($message); ?></div><?php endif; ?>
<section class="panel"><form class="filter-bar" method="get"><div class="search-box"><i class="bi bi-search"></i><input name="search" value="<?= e($search); ?>" placeholder="Search ID, name, or barangay"></div><select name="status"><option value="">All statuses</option><?php foreach (array('Pending','Approved','Completed','Rejected') as $option): ?><option value="<?= e($option); ?>" <?= $status === $option ? 'selected' : ''; ?>><?= e($option); ?></option><?php endforeach; ?></select><select name="assistance_type"><option value="">All assistance types</option><?php foreach (array('Financial Assistance','Medical Assistance','Educational Assistance','Solicitation','Other') as $option): ?><option value="<?= e($option); ?>" <?= $type === $option ? 'selected' : ''; ?>><?= e($option); ?></option><?php endforeach; ?></select><input type="date" name="date" value="<?= e($date); ?>"><button class="btn btn-dark" type="submit">Filter</button><?php if ($search || $status || $type || $date): ?><a class="clear-filter" href="requests.php">Clear</a><?php endif; ?></form><div class="table-wrap"><table><thead><tr><th>Request ID</th><th>Full Name</th><th>Barangay</th><th>Type</th><th>Amount</th><th>Date</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach ($requests as $request): ?><tr><td><strong class="request-code"><?= e($request['request_id']); ?></strong></td><td><?= e($request['full_name']); ?></td><td><?= e($request['barangay']); ?></td><td><?= e($request['assistance_type']); ?></td><td>PHP <?= e(format_amount($request['amount_requested'])); ?></td><td><?= e(date('M d, Y', strtotime($request['date_of_visit']))); ?></td><td><span class="status <?= e(status_class($request['status'])); ?>"><?= e($request['status']); ?></span></td><td><div class="action-links"><a href="view_request.php?id=<?= e($request['id']); ?>" title="View"><i class="bi bi-eye"></i></a><a href="edit_request.php?id=<?= e($request['id']); ?>" title="Edit"><i class="bi bi-pencil-square"></i></a><a href="update_status.php?id=<?= e($request['id']); ?>" title="Update status"><i class="bi bi-arrow-repeat"></i></a><form method="post" class="inline-form delete-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()); ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?= e($request['id']); ?>"><button type="submit" title="Delete"><i class="bi bi-trash3"></i></button></form></div></td></tr><?php endforeach; ?><?php if (!$requests): ?><tr><td colspan="8" class="empty-state"><i class="bi bi-inbox"></i><br>No requests match your filters.</td></tr><?php endif; ?></tbody></table></div></section>
<?php include __DIR__ . '/../inc/footer.php'; ?>
