<?php
require_once __DIR__ . '/../inc/auth.php'; require_once __DIR__ . '/../config/database.php';
$id = (int) ($_GET['id'] ?? $_POST['id'] ?? 0); $statement = $pdo->prepare('SELECT * FROM requests WHERE id = ?'); $statement->execute(array($id)); $request = $statement->fetch(); if (!$request) { http_response_code(404); exit('Request not found.'); }
$errors = array();
if ($_SERVER['REQUEST_METHOD'] === 'POST') { verify_csrf(); $new_status = $_POST['status'] ?? ''; if (!in_array($new_status, array('Pending','Approved','Completed','Rejected'), true)) { $errors[] = 'Please select a valid status.'; } elseif ($new_status === $request['status']) { $errors[] = 'Please select a different status.'; } else { try { $pdo->beginTransaction(); $update = $pdo->prepare('UPDATE requests SET status = ? WHERE id = ?'); $update->execute(array($new_status, $id)); $history = $pdo->prepare("INSERT INTO transaction_history (request_id, action, previous_status, new_status, processed_by) VALUES (?, 'Status updated', ?, ?, ?)"); $history->execute(array($id, $request['status'], $new_status, $_SESSION['full_name'])); $pdo->commit(); $_SESSION['success'] = 'Request status updated successfully.'; redirect('view_request.php?id=' . $id); } catch (Exception $error) { if ($pdo->inTransaction()) { $pdo->rollBack(); } $errors[] = 'The status could not be updated.'; } } }
$page_title = 'Update Status'; $active_page = 'requests'; include __DIR__ . '/../inc/header.php';
?>
<div class="detail-heading"><div><a class="back-link" href="view_request.php?id=<?= e($id); ?>"><i class="bi bi-arrow-left"></i> Back to Request</a><h2 class="section-title">Update request status</h2><p class="muted"><?= e($request['request_id']); ?> · <?= e($request['full_name']); ?></p></div><span class="status large-status <?= e(status_class($request['status'])); ?>"><?= e($request['status']); ?></span></div><?php if ($errors): ?><div class="alert alert-error"><i class="bi bi-exclamation-circle"></i><?= e(implode(' ', $errors)); ?></div><?php endif; ?><section class="panel status-panel"><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()); ?>"><input type="hidden" name="id" value="<?= e($id); ?>"><label for="status">New Status</label><select id="status" name="status" class="status-select"><?php foreach (array('Pending','Approved','Completed','Rejected') as $option): ?><option <?= $request['status'] === $option ? 'selected' : ''; ?>><?= e($option); ?></option><?php endforeach; ?></select><p class="muted status-help">This change will be recorded in transaction history as processed by <?= e($_SESSION['full_name']); ?>.</p><div class="form-actions"><a href="view_request.php?id=<?= e($id); ?>" class="btn btn-light">Cancel</a><button class="btn btn-primary" type="submit"><i class="bi bi-arrow-repeat"></i> Update Status</button></div></form></section>
<?php include __DIR__ . '/../inc/footer.php'; ?>
